var guessNumber = 1;
var id = function(id) { return document.getElementById(id); };
var word;
var yellow = "#B59F39";
var green = "#538D4E";
var correctLetters = 0;
var score = 0;
var highScore = 0;
var row =1;
var guessedLetters = [];
var column = 1;
var keyboardGuess = false;