var guessNumber = 1;
var id = function(id) { return document.getElementById(id); };
var word;
var yellow = "#B59F39";
var green = "#538D4E";
var score = 0;
var highScore = 0;
var position = 1;
var row = 1;
var guessedLetters = [];
var correctLetters = [];
var column = 1;
